### ISSUE TITLE
[BUG] Returning status OK when card not found

### ISSUE THREAD

**Issue by williamokano** [williamokano/magic-card-prices#1]
The status is being return as ok when a card is not found. It could be by an http error and/or by looking for the wrong name of the card.

For example, Instead of looking for "Nissa, Worldwaker" you look for "Nissa Worldwaker" (without the comma) no prices nor name will be returned (in other words, error) but the status of the API will be returned http 200 and in the JSON {status: "ok"}.

Needs fixing!

**Comment by stenioaraujo** [comment]
If you don't return the status ok for a 200 response, I think it's fine. You could only return a error description if it's not a 200.

**Comment by williamokano** [comment]
I was thinking, some frameworks throw an error when they get an http code different from 200, so I'm thinking to only fix the status and add an error msg.
